### ISSUE TITLE
How does iter work?

### ISSUE THREAD

**Issue by fooxed** [dtolnay/inventory#19]
Hey this is a cool project. Thank you for sharing. Trying to understand how it works, but got confused in the ITER. 

Questions: 

1. Why use `IntoIterator for iter<T>`? You seem to be delegating to `into_iter<T: Collect>() -> Iter<T>`. Why are you using the a foreign, zero-sized ` iter<T>` type alias then? Not understanding how the crate you use in the private mod tying this together.   
2. Are there perhaps any other ways you have experimented using this crate that could make it easier to understand use cases? Looked on crates.io, but this seems to be the only dependent repo.
3. Why is ITER unused? Perhaps confused by anonymous function syntax. 

Thank you!

**Comment by dtolnay** [comment]
I am a firm believer that the sketchiness of the API needs to reflect the sketchiness of the implementation. Putting a straight laced API on something like what this crate does is a bad deal. This was the API that was a suitable fit.
