### ISSUE TITLE
Distribute configuration file segments using inventory

### ISSUE THREAD

**Issue by mainrs** [dtolnay/inventory#20]
I have a lot of modules (~100) that each declare their own configuration sub-section that implement `serde::Deserialize`. I now have to combine those sub-sections into one huge configuration struct. I do not want to introduce coupling again and dependent on all of those crates manually to just declare a field inside a config struct:

```rust
struct GlobalConfig {
    field_module_a: ModuleAConfig,
    // more of these ...
}
```

Is it somehow possible to combine `serde` and `inventory`/`linkme` to decouple the configuration file and somehow generate it at compile-time? I basically need one single huge config struct that I can pass around instead of having to deserialize the same file 100 times just to get the right structs.
I tried multiple approaches but couldn't really figure anything out that worked properly.

Can this be achieved? If yes, any hints on how to approach it? :)

**Comment by dtolnay** [comment]
Yes either crate would work. It would help if you shared all the ways you tried.

**Comment by SirWindfield** [comment]
My current "working" solution is to just iterate over the configs at runtime and deserialize each of them using the same file content. Which works ok-ish but feels wrong.

The only way I see it working as intended (adding the fields to the `GlobalConfig` struct itself before compiling the `GlobalConfig` struct) is a `build.rs` file that uses `proc_macro2` to generate my configuration struct. The build script would then iterate over the submitted structs using the `inventory` crate and add the fields to it, writing the result to a source file that I just include into the code base.

Maybe there is an easier way to do this, but that is the only one I cam up with that allows me to actually define all the fields inside the struct.

**Comment by dtolnay** [comment]
Sorry that I was not able to get back to this to provide guidance. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community (Discord, Users forum, possibly the Rust subreddit).
