### ISSUE TITLE
Doesn't work when compiling the binary in debug mode

### ISSUE THREAD

**Issue by mainrs** [dtolnay/inventory#24]
I always have problems when running my compiled binary in debug mode. For some reason `inventory`'s iterator doesn't return anything. I always have to run the binary in release mode. This makes it harder to fix panics as the lines where they happen are unknown and not displayed in the stacktrace.

Not sure if this is related to #7...

__OS:__ Windows 10 2004
__rustc:__ 1.46.0 (does happen with earlier versions as well)
__inventory:__ 0.1.8

**Comment by SirWindfield** [comment]
Disabling incremental builds does resolve this:
```toml
# Cargo.toml
[profile.dev]
incremental = false
```

**Comment by SirWindfield** [comment]
Doing a little more research and it seems that this problem is blocked by https://github.com/rust-lang/rust/issues/47384. Someone also mentioned the `incremental = false` fix there: https://github.com/rust-lang/rust/issues/47384#issuecomment-631790924

**Comment by thegwan** [comment]
Also came across this issue. It seems that in release mode things work ok, but in debug mode the module in the crate has to actually be used for it to be properly submitted to the inventory

**Comment by mathstuf** [comment]
I came across this behavior recently. It was working in the 2015 edition, but broke when changing to the 2018 edition.

**Comment by dtolnay** [comment]
This is fixed in rustc 1.62.0 / inventory 0.3.0.
