### ISSUE TITLE
please include LICENSE-* files in published -impl crates

### ISSUE THREAD

**Issue by decathorpe** [dtolnay/inventory#27]
The inventory-impl crates published to crates.io do not contain the LICENSE-APACHE and LICENSE-MIT files. For both those licenses, it's necessary to distribute the license text alongside the covered source code. This creates issues for (linux) distributions which redistribute the crate source code.
Adding symlinks from the `impl` directory to the files in the root of the repository should be enough to fix this, if you're running `cargo publish` from linux or mac OS.

**Comment by dtolnay** [comment]
Thanks for reporting. I published inventory-impl 0.1.10 with the license files.

**Comment by decathorpe** [comment]
Wow, that was fast. Thanks!
