### ISSUE TITLE
Add a note to readme explaning how this works under the hood

### ISSUE THREAD

**Issue by matklad** [dtolnay/inventory#3]
I've literally re-checked 1.31 relnote thinking "wait, wat, they've added life before main to Rust in 1.31?!" :rofl: OTOH, it was fun to figure out the impl

**Comment by dtolnay** [comment]
Thanks, definitely necessary. I added a small writeup in https://github.com/dtolnay/inventory/tree/master#how-it-works. Is there anything you would explain in more detail?

I linked to the `ctor` readme which explains the mechanics on their end.

**Comment by matklad** [comment]
LGTM!

It probably makes sense to write something about platform restrictions as well? Does WASM have life before main?

**Comment by dtolnay** [comment]
Done. It looks like ctor just does nothing on wasm for now.
