### ISSUE TITLE
doesn't work inside module

### ISSUE THREAD

**Issue by mimoo** [dtolnay/inventory#34]
Hey @dtolnay, thanks a lot for this crate.

I'm trying to register submits from different modules, and it only works at the top level. Am I missing something?

```rust
  inventory::submit! {
      OcamlFunc::new("something") # this works
  }

  pub mod inside_mod {
      inventory::submit! {
          super::OcamlFunc::new("something_else") # this doesn't appear in the iter
      }
  }
```

**Comment by korrat** [comment]
@mimoo Did you figure out what was causing your issue? Could you help me understand what went wrong?

**Comment by mimoo** [comment]
no, I ended up using another crate (const-random)
