### ISSUE TITLE
Unsound usages of unsafe implementation from immut to mut

### ISSUE THREAD

**Issue by llooFlashooll** [dtolnay/inventory#73]
Hi, I am scanning the inventory in the latest version with my own static analyzer tool.

Unsafe conversion found at: src/lib.rs:196:27: 196:58
``` rust
let new_ptr = new as *const Node as *mut Node;

unsafe fn submit(&'static self, new: &'static Node) {
    let mut head = self.head.load(Ordering::Relaxed);
    loop {
        unsafe {
            *new.next.get() = head.as_ref();
        }
        let new_ptr = new as *const Node as *mut Node;
        match self
            .head
            .compare_exchange(head, new_ptr, Ordering::Release, Ordering::Relaxed)
        {
            Ok(_) => return,
            Err(prev) => head = prev,
        }
    }
}
```

This would potentially cause [undefined behaviors](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) in Rust. I am reporting this issue for your attention.
Probably can further wrap it into unsafe code block. This is just a tiny issue to conclude.

**Comment by dtolnay** [comment]
This is the second low-effort, incorrect report you have filed on my repos, and I have seen at least 3 more similarly poor issues you have opened recently in other repos I follow.

Please do not open another issue on any repo owned by me or you will be banned.
